name: marvel_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  provider:
  yaml: ^2.2.1
  rxdart: ^0.25.0
  flutter_secure_storage: ^3.3.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1


  cupertino_icons: ^1.0.2
  hidden_drawer_menu: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  # Imágenes y demás
  assets:
    - lang/
    - assets/images/


